### ISSUE TITLE
System.IO.DirectoryNotFoundException Error

### ISSUE THREAD

**Issue by enzirin** [starjet/Msute_Cst#2]
Hello. I am well-aware that this program/repository has not been updated in about two years, but I'd like to point this issue out, as I'd like to actually make this program work. I did some research regarding LoS's `.cst` files, but very little info was found, other than its file structure being changed or something like that. When I tried your program, I get a "`System.IO.DirectoryNotFoundException Error`".

I wonder if there's a work-around this error? Or if this is the final iteration of your program?

Hope to hear from you soon!

**Comment by starjet** [comment]
I haven't touched LoS in a while so I can't say for sure if this works with the latest version of the game, but that error likely means you're missing the LocalData folder.
Get the latest release from https://github.com/starjet/Msute_Cst/releases and that should contain that folder.

**Comment by enzirin** [comment]
Yeah, I figured. It actually does work on the latest version, but only up to a certain degree, before hitting the `"403 Forbidden Error"`. It might be due to the aforementioned changes in the file structure for LoS's `.csv` file, but I'm also suspecting the .json file in the LocalData Folder, since proper credentials are needed to access hidden files like that. I could be mistaken, though.

That was a fast reply, by the way. Thanks for helping me out! Even if you haven't touched the game and this repository in a while.

**Comment by starjet** [comment]
Okay, I tested with the latest baseURL myself.
Seems some CSTs are not available in the server anymore. ("403 Forbidden" is simply an error that's returned from the CDN when the file doesn't exist. There's no actual security here.)
Maybe they have been replaced by others. Will need to find out the current set of .csv filenames.
Unfortunately, I don't have the time to do an update to this right now, so I can't help you anytime soon. But you might be able to find the right files by using something like Fiddler or simply by looking inside the game files in a rooted Android device.

**Comment by enzirin** [comment]
That's okay, but I really appreciate that you put effort into helping me out on this but testing out the latest baseURL, especially with a program that's about two y/o.

Anyway, that's actually the current concern— finding the current set of `.csv` files [the link, that is]. I have also used both Fiddler and Process Hacker, and I think I might've actually found it, but the file itself does not have a "working extension". Putting the link into a browser, it just automatically downloads as an extension-less file. Opening it up in a Hex Editor, however, shows up some interesting stuff— like `"FileID, Path, Size"`, which kinda sounds like headers in a `database file.` I was able to see the names of the characters, but the rest looks like gibberish, though it quite resembles links. I will admit, however, that I'm more adept at Front-End Developing than I am at Back-End Developing.

I apologize for still continuing about this. It's been made clear to me that I put effort in the strangest of things, so I really appreciate that you give some time on this matter ❤️

**Comment by starjet** [comment]
Can you post those links you found?

**Comment by enzirin** [comment]
This is the link that downloads the extension-less file using the latest baseURL:
`https://d2qkdj9w29igl.cloudfront.net/v1/2020060801-egH7tLKG5raprY8KzgYCrhrQaB40a5lg/asset_bundles/android/android`

The rest of the links I found are those directly referencing the individual assets [chibichara images and stuff], and some only shows `d2qkdj9w29igl.cloudfront.net` [not even the actual baseURL, just the cloudfront.net], and based on what I've been reading, they seem to be "tunneling" or something [even Process Hacker running as Admin can't see through, or I'm missing something].

**Comment by starjet** [comment]
So, looking through the data of the game, seems that
"Card.cst", "Chara.cst", "Unit.cst"
are files that are simply no more in the game or its server.
All other file related CSTs are getting downloaded correctly and URLs generated for them.
But the question now is, what do you intend to do with the CSTs? How I can help you will depend on that.

**Comment by enzirin** [comment]
Sorry for the fairly late reply!

I see, so there are less `.cst` files now compared to the past versions. I looked through the .cst files from the data I extracted from the rooted device, and those .csts really aren't there anymore.

My purpose is actually to obtain the 3D Models & Dance Motions and port them to a different 3D Program [noting that this is purely for entertainment purposes, and have no intention of redistributing the 3D Models I port], but if the other `.cst` files are being downloaded correctly from the servers, then I believe I actually have the latest URLs for the 3D Models [`Resources.cst`, and kinda baffled that there's only like 12-15 3D models per idol, considering there's a ridiculous amount of card art for each of them, but I suppose there's like 46 individual idols in the game, so.... guess I was hoping there were more costumes, but I'm not about to play through the entire game just to find that out goodness XD I'm happy with what I have now]

Which I guess means this is it, actually. I apologize for the trouble you had to go through because this person was too determined to obtain the 3D Models and Dance Motions, but I'm glad and thankful you actually went through said trouble to help me out.

Thanks again for helping me out! I really appreciate it!! ❤️

**Comment by starjet** [comment]
Yes. Resources.cst should have everything you need. This program can generate a direct set of URLs off it as well. So you can download stuff directly off the server.
But note that not every card art you see has a corresponding outfit. There are cards that simply don't come with a custom outfit so defaults to a common 3D model.

**Comment by enzirin** [comment]
Yeah, realized that it wasn't like Dynasty Warriors NEXT, in which every card has a corresponding 3D Model to it.

Thanks again! ❤️
